[tool.uv.workspace]
members = [
    "apps/api",
    "apps/bot",
    "libs/sdk",
    "docs",
]

[tool.uv.sources]
genjishimada-sdk = { workspace = true }

[dependency-groups]
dev = [
    "pytest-mock>=3.15.1",
]
dev-common = [
    "basedpyright>=1.29.4",
    "ruff>=0.12.0",
    "complexipy>=4.0.2",
]

[tool.ruff]
extend-exclude = [
    "apps/api/conftest.py",
    "apps/api/tests",
    "apps/bot/conftest.py",
    "apps/bot/tests",
]
line-length = 120
target-version = "py313"

lint.select = [
    "E",
    "F",
    "W",
    "A",
    "PL",
    "I",
    "SIM",
    "RUF",
    "ASYNC",
    "C4",
    "INP",
    "ERA",
    "SLF",
    "PIE",
    "PYI",
    "ANN",
    "N",
    "D",
]
lint.ignore = [
    "ANN002",
    "ANN003",
    "D203",
    "D100",
    "D101",
    "D104",
    "D107",
    "RUF012",
    "TC002",
    "D213",
    "TC001",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"apps/api/conftest.py" = ["ALL"]
"apps/api/tests/*.py" = ["ALL"]
"apps/api/tests/**/*.py" = ["ALL"]
"apps/bot/conftest.py" = ["ALL"]
"apps/bot/tests/*.py" = ["ALL"]
"apps/bot/tests/**/*.py" = ["ALL"]

[tool.basedpyright]
exclude = [
    "apps/api/tests",
    "apps/api/conftest.py",
    "apps/bot/tests",
    "apps/bot/conftest.py",
]
